version: '3.8'

services:
  database:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_now
      MYSQL_USER: foodnowuser
      MYSQL_PASSWORD: foodnowcontrasenia
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend-rest:
    image: basgomcesar/backend-foodnow:1.3 # Imagen ya creada
    container_name: backend-rest
    restart: always
    environment:
      DB_HOST: localhost
      DB_USER: foodnowuser
      DB_PASSWORD: foodnowcontrasenia
      DB_NAME: food_now
    ports:
      - "3000:3000"
    depends_on:
      - database

  backend-grpc:
    image: basgomcesar/backend-grpc:1.1 # Imagen ya creada
    container_name: backend-grpc
    restart: always
    environment:
      DB_HOST: localhost
      DB_USER: usefoodnowuserr
      DB_PASSWORD: foodnowcontrasenia
      DB_NAME: food_now
    ports:
      - "50051:50051"
    depends_on:
      - database

volumes:
  db_data:
